apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    environment: pre-prod
    steps:
      - name: Deploy SampleApp-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].digest }}
          target-environment: pre-prod
          name: SampleApp-Frontend

      - name: Deploy SampleApp-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].digest }}
          target-environment: pre-prod
          name: SampleApp-Backend

      - name: Deploy SampleApp-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].digest }}
          target-environment: pre-prod
          name: SampleApp-APIs
  prod:
    needs: pre-prod
    environment: prod
    steps:
      - name: Deploy SampleApp-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-Frontend']['SampleApp-Frontend'].digest }}
          target-environment: prod
          name: SampleApp-Frontend

      - name: Deploy SampleApp-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-Backend']['SampleApp-Backend'].digest }}
          target-environment: prod
          name: SampleApp-Backend

      - name: Deploy SampleApp-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['SampleApp-APIs']['SampleApp-APIs'].digest }}
          target-environment: prod
          name: SampleApp-APIs
